language: java
jdk:
  - oraclejdk8
addons:
  sauce_connect: true
before_install:
  - nvm install 5
  - npm install -g lerna@2.0.0-beta.13
  - lerna bootstrap
install:
  - npm i
before_script:
  - npm run compile
script: gulp test:saucelabs
env:
  global:
  - secure: PpcPWojQPVS26DbyY8ylKMFexGUofRKxwgssYWeWCan/XB9xl1Z1MbRIxPdL8Jdz+5J2iZ5dOBmEWGJ4IniIm+L66X60jkZPjB1nZ8PxaxJJ6cs5g3fZRYHRvSR5BWPEQ+x7q8sSc0lBRf0H4BhDxBA9XtDo27WEDugbDgCJZk/57j7ayCBhmjLnbve7b/eGqDP/dWNf9foeM1iCsWoGCJtZobhHtLnSg1bpTS3rP9dsv5FGWG8UaGl3/E1VItLuzgsphT1kaEneiNDv9+KSzdTOGcBYJYZB1MEmT1LMGUcGu2B4M2jmCMWaSiW+FJ5UKqAAPw26I3nKzX1yfViCbmjC49W2c0zQZg8XWv96N1aaNF74x/AJKiFPUZ4wjVN1OxB4xsCEpXt3WD3i4h0rt83gkkwuk0EUv7PuwIA5fKDXh161wziYiz6gDC7zM2ybRttJYeVn+TTeKcJOLcrF+oolICgX/RWOiA1EMaNYqrQrfmUzmLJ5bIg7ZgYcT6Dh63vzo6po6vOePQ3sHU70uSmtmisKe1s4n4P3oi+2htZkALWMv/Xi7uk7s+7p5lzz2H4h6VpCP22sTbRHYNXJFctFWyUIgOrL+76Cr4cF7gnCagRyy6EEEevV/fN3W4hRJ+L6xUGr3PqRu8NovtpP9unVs3uUeVD4FsTbB8vlxtI=
  - secure: vT2IPAbPEbf0akEGFffljSEATY+U5aAyCs7gXWq90crYB3rdDcuMTJHVWCDAWwHAstWXWd+D6X1vlbse8s42tfv2R6sdsite8DPhzXekrOhZq4AYzcx4oS2nU+d1w2UIPBjqxJf7+sHEr/HOHOaw38jeeHIoj6WL8OMdSqWBQzYgWaMa9vEvEWsGUjmSCl5VH7F+7k0xa690Zf8QWrXxSUAxz9AghkyALDAHkRNbcU82JZs0Mwed53JlNoP2KmeBIHxtg6JuCcw/oPyV/exjOYEKJwqqVU0g08JfVt7pcXO4EjLYP9pbi5YZT0vtsSHIEqdmHxUCbgeyrXM7N5xn6+B9OPjc76jKnYUqOtXpy6qnd049an6NP9O2mYD98cRCiqo6LdGDNnUrDzA3FM/iUf40GaiVazp60ieJUJLjSXNF18PHkU2g7v+pRbgxvCYs+MmES3m0jTYpBCmXNl0MydnUEzse9nmL+3OJyCq56qaYbLz+OLlxvJ6ePZDGqXuj29BN2Bh18H8ZgbDSykH7kTivCE2UGZzmAhYxlvZy9nvAsVhI7h/WoeUHvkO6U0oBE4awzzP4cXNCo3ruf8vajuO6dtpLOBK2zh4GgnCeer+Wr5K/R5X2OUQ6N1a2JOdzT8gwp5bfEMZvRj5Ie3ptEU+47n82wtV/6j+Qt76Ff0U=
